# Generated by Django 4.2.16 on 2026-02-23 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="+91",
                        help_text="Phone country code with + prefix (e.g., +91, +1, +44)",
                        max_length=5,
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        help_text="Mobile number without country code",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_alerts_email", models.BooleanField(default=True)),
                ("job_alerts_mobile", models.BooleanField(default=False)),
                ("feature_updates_email", models.BooleanField(default=True)),
                ("feature_updates_mobile", models.BooleanField(default=False)),
                ("newsletters_email", models.BooleanField(default=True)),
                ("newsletters_mobile", models.BooleanField(default=False)),
                ("policy_changes_email", models.BooleanField(default=True)),
                ("policy_changes_mobile", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
    ]
