# Generated by Django 4.2.16 on 2026-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_add_userprofile_and_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Unique identifier used in code to look up this template (e.g., "password-reset").',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable template name (for admin display).",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("notification", "Notification"),
                            ("marketing", "Marketing"),
                            ("system", "System"),
                        ],
                        default="system",
                        help_text="Template category for filtering in admin.",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text='Email subject line. Supports Django template variables (e.g., "{{ app_name }} — Password Reset").',
                        max_length=255,
                    ),
                ),
                (
                    "html_body",
                    models.TextField(
                        help_text="HTML email body. Use Django template syntax for variables: {{ username }}, {{ reset_link }}, etc."
                    ),
                ),
                (
                    "plain_text_body",
                    models.TextField(
                        blank=True,
                        help_text="Plain-text fallback (auto-generated from HTML if left blank).",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Internal note explaining when this template is used.",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive templates cannot be sent."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["category", "name"],
            },
        ),
    ]
