# Generated by Django 4.2.16 on 2026-02-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_email_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Plan display name (e.g., "Free", "Pro", "Enterprise").',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Plan identifier used in code (e.g., "free", "pro").',
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description shown to users.",
                        max_length=500,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("lifetime", "Lifetime"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price in INR (0 for free tier).",
                        max_digits=8,
                    ),
                ),
                (
                    "analyses_per_month",
                    models.IntegerField(
                        default=0, help_text="Max analyses per month (0 = unlimited)."
                    ),
                ),
                (
                    "api_rate_per_hour",
                    models.IntegerField(
                        default=200, help_text="Max general API requests per hour."
                    ),
                ),
                (
                    "max_resume_size_mb",
                    models.IntegerField(
                        default=5, help_text="Max resume file size in MB."
                    ),
                ),
                (
                    "max_resumes_stored",
                    models.IntegerField(
                        default=5,
                        help_text="Max resumes stored at once (0 = unlimited).",
                    ),
                ),
                (
                    "pdf_export",
                    models.BooleanField(
                        default=True, help_text="Can export analysis as PDF report."
                    ),
                ),
                (
                    "share_analysis",
                    models.BooleanField(
                        default=True, help_text="Can generate public share links."
                    ),
                ),
                (
                    "job_tracking",
                    models.BooleanField(
                        default=True, help_text="Can use job tracking features."
                    ),
                ),
                (
                    "priority_queue",
                    models.BooleanField(
                        default=False,
                        help_text="Analyses processed in priority Celery queue.",
                    ),
                ),
                (
                    "email_support",
                    models.BooleanField(
                        default=False, help_text="Has access to email support."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive plans cannot be assigned to new users.",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Sort order on pricing page (lower = first).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Current subscription plan. NULL = Free tier defaults.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.plan",
            ),
        ),
    ]
