# Generated by Django 4.2.16 on 2026-02-26 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_add_plan_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.SlugField(
                        help_text='Action identifier (e.g., "resume_analysis").',
                        unique=True,
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(
                        default=1, help_text="Credits consumed per action."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of this action.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Cost",
                "verbose_name_plural": "Credit Costs",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0, help_text="Current credit balance."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="credits_per_month",
            field=models.PositiveIntegerField(
                default=0, help_text="Credits granted each billing cycle (0 = none)."
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="job_notifications",
            field=models.BooleanField(
                default=False, help_text="Can receive job alert notifications."
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_credits_balance",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max credits from monthly grants (0 = no cap). Top-ups bypass this cap.",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="topup_credits_per_pack",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Credits per top-up pack (0 = top-up not allowed for this plan).",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="topup_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per top-up pack in INR.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan to switch to after current billing cycle expires (for downgrades).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_users",
                to="accounts.plan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_valid_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current billing cycle ends. NULL for free plans.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive = credit, negative = debit."
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(
                        help_text="Wallet balance after this transaction."
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("plan_credit", "Monthly Plan Credit"),
                            ("topup", "Top-Up Purchase"),
                            ("analysis_debit", "Analysis Debit"),
                            ("refund", "Refund"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("upgrade_bonus", "Upgrade Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Links to analysis ID or other context.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "-created_at"],
                        name="accounts_wa_wallet__ff11a4_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="accounts_wa_transac_5b9160_idx",
                    ),
                ],
            },
        ),
    ]
