# Generated by Django 4.2.16 on 2026-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_creditcost_wallet_plan_credits_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_job_alerts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Max active job alerts allowed (0 = not permitted, Pro = 3).",
            ),
        ),
    ]
