# Generated by Django 4.2.16 on 2026-02-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_plan_max_job_alerts"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpaySubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(
                        help_text="Razorpay subscription_id.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "razorpay_plan_id",
                    models.CharField(
                        help_text="Razorpay plan_id used to create this subscription.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authenticated", "Authenticated"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("halted", "Halted"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "current_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of current billing period.",
                        null=True,
                    ),
                ),
                (
                    "current_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of current billing period.",
                        null=True,
                    ),
                ),
                (
                    "short_url",
                    models.URLField(
                        blank=True,
                        help_text="Short URL for payment (provided by Razorpay).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="razorpay_subscriptions",
                        to="accounts.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Razorpay Subscription",
                "verbose_name_plural": "Razorpay Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="RazorpayPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("subscription", "Subscription"), ("topup", "Top-Up")],
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay order_id (for one-time top-ups).",
                        max_length=100,
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay payment_id (set after payment completes).",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay signature for verification.",
                        max_length=255,
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Razorpay subscription_id (for subscription payments).",
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Amount in paise (₹499 = 49900 paise)."
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (plan_slug, quantity, etc.).",
                    ),
                ),
                (
                    "webhook_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True if this payment was confirmed via webhook.",
                    ),
                ),
                (
                    "credits_granted",
                    models.BooleanField(
                        default=False,
                        help_text="True if credits/plan have been applied for this payment.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Razorpay Payment",
                "verbose_name_plural": "Razorpay Payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_ra_user_id_458339_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accounts_ra_status_15a13b_idx",
                    ),
                ],
            },
        ),
    ]
