# Generated by Django 4.2.16 on 2026-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_razorpay_payment_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaypayment",
            name="razorpay_payment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Razorpay payment_id (set after payment completes).",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
