# Generated by Django 4.2.16 on 2026-02-27 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_add_webhook_event_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaysubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="razorpay_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
