# Generated by Django 4.2.16 on 2026-02-27 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_change_subscription_to_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="agreed_to_data_usage",
            field=models.BooleanField(
                default=True,
                help_text="User acknowledged AI data processing and Data Usage Policy.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agreed_to_terms",
            field=models.BooleanField(
                default=True,
                help_text="User agreed to Terms of Service and Privacy Policy.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="User opted in to marketing emails, tips, and newsletters.",
            ),
        ),
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_privacy", "Terms & Privacy Policy"),
                            ("data_usage_ai", "Data Usage & AI Disclaimer"),
                            ("marketing_newsletter", "Marketing & Newsletter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "agreed",
                    models.BooleanField(
                        help_text="True = opted in / agreed; False = withdrew consent."
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of the legal document the user agreed to.",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Log",
                "verbose_name_plural": "Consent Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type", "-created_at"],
                        name="accounts_co_user_id_bc47a7_idx",
                    )
                ],
            },
        ),
    ]
