# Generated by Django 4.2.16 on 2026-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_consent_log_and_profile_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_provider",
            field=models.CharField(
                choices=[("email", "Email"), ("google", "Google")],
                default="email",
                help_text="How the user signed up (email registration or Google OAuth).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Profile picture URL (from Google or uploaded). Blank means no avatar.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_sub",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google account unique subject identifier (from ID token).",
                max_length=255,
            ),
        ),
    ]
