# Generated by Django 4.2.16 on 2026-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_google_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="razorpay_plan_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current Razorpay plan_id. Auto-managed — created via API when price/billing changes.",
                max_length=100,
            ),
        ),
    ]
