# Generated by Django 4.2.16 on 2026-02-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_add_razorpay_plan_id_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(
                blank=True, default="", help_text="GitHub profile URL.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="LinkedIn profile URL.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Personal website or portfolio URL.",
                max_length=300,
            ),
        ),
    ]
