# Generated by Django 4.2.16 on 2026-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_fix_razorpay_plan_id_server_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original price in INR before discount (0 = no discount). Shown as strikethrough on frontend.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_job_alerts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Deprecated — no longer enforced. Job alerts are gated by job_notifications flag only.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discounted/current price in INR (what users actually pay).",
                max_digits=8,
            ),
        ),
    ]
