# Generated by Django 4.2.16 on 2026-02-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_add_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="premium_templates",
            field=models.BooleanField(
                default=False, help_text="Can use premium resume templates."
            ),
        ),
    ]
