# Generated by Django 4.2.16 on 2026-03-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_premium_templates_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text='City of residence (e.g. "Bangalore", "Mumbai").',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                default="India",
                help_text="Country of residence. Used as primary geo filter for feed & analytics.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(
                blank=True,
                default="",
                help_text='State / province / region (e.g. "Karnataka", "California").',
                max_length=100,
            ),
        ),
    ]
