# Generated by Django 4.2.16 on 2026-07-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_wallettransaction_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="max_job_alerts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Maximum number of job alerts allowed. 0 = no access. Pro plan = 5.",
            ),
        ),
    ]
