# Generated by Django 4.2.16 on 2026-02-22 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("resume_text", models.TextField(blank=True)),
                (
                    "jd_input_type",
                    models.CharField(
                        choices=[
                            ("text", "Raw Text"),
                            ("url", "URL"),
                            ("form", "Structured Form"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "jd_text",
                    models.TextField(blank=True, help_text="Raw job description text"),
                ),
                ("jd_url", models.URLField(blank=True, help_text="URL to job posting")),
                (
                    "jd_role",
                    models.CharField(
                        blank=True, help_text="Job role/title", max_length=255
                    ),
                ),
                ("jd_company", models.CharField(blank=True, max_length=255)),
                (
                    "jd_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated required skills"
                    ),
                ),
                (
                    "jd_experience_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("jd_industry", models.CharField(blank=True, max_length=255)),
                (
                    "jd_extra_details",
                    models.TextField(
                        blank=True, help_text="Any other relevant details"
                    ),
                ),
                ("resolved_jd", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("ats_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ats_score_breakdown", models.JSONField(blank=True, null=True)),
                ("keyword_gaps", models.JSONField(blank=True, null=True)),
                ("section_suggestions", models.JSONField(blank=True, null=True)),
                ("rewritten_bullets", models.JSONField(blank=True, null=True)),
                ("overall_assessment", models.TextField(blank=True)),
                ("ai_provider_used", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
