# Generated by Django 4.2.16 on 2026-02-22 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="pipeline_step",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pdf_extract", "Extracting PDF"),
                    ("jd_scrape", "Scraping JD"),
                    ("llm_call", "Calling LLM"),
                    ("parse_result", "Parsing Result"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScrapeResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.URLField(max_length=2048)),
                ("markdown", models.TextField(blank=True)),
                ("json_data", models.JSONField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_sent",
                    models.TextField(
                        blank=True, help_text="Exact prompt/messages sent to the LLM"
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, help_text="Raw LLM output as-is"),
                ),
                (
                    "parsed_response",
                    models.JSONField(
                        blank=True, help_text="Validated JSON result", null=True
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="llm_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="analyzer.llmresponse",
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="scrape_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="analyzer.scraperesult",
            ),
        ),
        migrations.AddIndex(
            model_name="scraperesult",
            index=models.Index(
                fields=["source_url", "status", "-created_at"],
                name="analyzer_sc_source__3735cb_idx",
            ),
        ),
    ]
