# Generated by Django 4.2.16 on 2026-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_resumeanalysis_pipeline_step_scraperesult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="celery_task_id",
            field=models.CharField(
                blank=True, help_text="Celery task ID for tracking", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="report_pdf",
            field=models.FileField(
                blank=True,
                help_text="Pre-generated PDF report (stored in R2)",
                upload_to="reports/",
            ),
        ),
    ]
