# Generated by Django 4.2.16 on 2026-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_resumeanalysis_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_re_user_id_b75419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["status", "updated_at"], name="analyzer_re_status_8f70e4_idx"
            ),
        ),
    ]
