# Generated by Django 4.2.16 on 2026-02-23 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0004_add_resumeanalysis_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hex digest for deduplication",
                        max_length=64,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="resumeanalysis",
            options={"default_manager_name": "objects", "ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Soft-delete timestamp; NULL = active",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["user", "deleted_at"], name="analyzer_re_user_id_3bb96e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeanalysis",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="analyzer_re_user_id_51be1e_idx",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                help_text="Deduplicated resume reference",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyses",
                to="analyzer.resume",
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="analyzer_re_user_id_3b53f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resume",
            constraint=models.UniqueConstraint(
                fields=("user", "file_hash"), name="unique_resume_per_user"
            ),
        ),
    ]
