# Generated by Django 4.2.16 on 2026-02-23 03:44
"""
Data migration: create Resume rows from existing ResumeAnalysis.resume_file
values, deduplicate by SHA-256 hash per user, and link analyses back.

For analyses whose files are in remote storage (R2), we compute hash from the
stored file. For missing/inaccessible files, a placeholder hash is used so the
migration never fails.
"""
import hashlib
import uuid

from django.db import migrations


def populate_resumes(apps, schema_editor):
    """Create Resume rows from existing resume_file fields on ResumeAnalysis."""
    Resume = apps.get_model('analyzer', 'Resume')
    # Use all_objects-style unfiltered query since the default manager may filter
    ResumeAnalysis = apps.get_model('analyzer', 'ResumeAnalysis')

    # Group analyses by user for dedup
    analyses = ResumeAnalysis.objects.filter(
        resume__isnull=True,
    ).exclude(resume_file='').select_related('user')

    # Cache: (user_id, file_hash) → Resume instance
    seen = {}

    for analysis in analyses.iterator():
        file_hash = _compute_hash_safe(analysis.resume_file)
        cache_key = (analysis.user_id, file_hash)

        if cache_key in seen:
            resume = seen[cache_key]
        else:
            # Check DB in case a previous run already created it
            resume = Resume.objects.filter(
                user_id=analysis.user_id, file_hash=file_hash,
            ).first()
            if not resume:
                resume = Resume.objects.create(
                    id=uuid.uuid4(),
                    user_id=analysis.user_id,
                    file=analysis.resume_file.name,
                    file_hash=file_hash,
                    original_filename=analysis.resume_file.name.split('/')[-1],
                    file_size_bytes=_get_size_safe(analysis.resume_file),
                )
            seen[cache_key] = resume

        analysis.resume = resume
        analysis.save(update_fields=['resume'])


def _compute_hash_safe(file_field):
    """Compute SHA-256 from stored file; return placeholder on failure."""
    try:
        hasher = hashlib.sha256()
        file_field.open('rb')
        for chunk in file_field.chunks():
            hasher.update(chunk)
        file_field.close()
        return hasher.hexdigest()
    except Exception:
        # File might not be accessible (deleted from R2, local dev, etc.)
        # Use the file name as a fallback deterministic hash
        return hashlib.sha256(file_field.name.encode()).hexdigest()


def _get_size_safe(file_field):
    """Get file size; return 0 on failure."""
    try:
        return file_field.size
    except Exception:
        return 0


def reverse_noop(apps, schema_editor):
    """Reverse is a no-op — Resume rows can remain; FK is nullable."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0005_add_resume_model_soft_delete"),
    ]

    operations = [
        migrations.RunPython(populate_resumes, reverse_noop),
    ]
