# Generated by Django 4.2.16 on 2026-02-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_populate_resume_from_existing"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="share_token",
            field=models.UUIDField(
                blank=True,
                help_text="Public share token — when set, analysis is viewable at /api/shared/<token>/",
                null=True,
                unique=True,
            ),
        ),
    ]
