# Generated by Django 4.2.16 on 2026-02-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0007_add_share_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_url",
                    models.URLField(
                        help_text="URL of the job posting", max_length=2048
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Job title/role", max_length=500
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Job description snippet"),
                ),
                (
                    "relevance",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("relevant", "Relevant"),
                            ("irrelevant", "Irrelevant"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="User feedback on job relevance",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the job was found (e.g. linkedin, indeed)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resume used for matching this job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="analyzer.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analyzer_jo_user_id_befbd7_idx",
                    ),
                    models.Index(
                        fields=["user", "relevance"],
                        name="analyzer_jo_user_id_3af7d8_idx",
                    ),
                ],
            },
        ),
    ]
