# Generated by Django 4.2.16 on 2026-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0008_add_job_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="ats_score_breakdown",
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="ats_disclaimers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="keyword_gaps",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="overall_assessment",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="rewritten_bullets",
        ),
        migrations.RemoveField(
            model_name="resumeanalysis",
            name="section_suggestions",
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="formatting_flags",
            field=models.JSONField(
                blank=True, help_text="Array of formatting issues", null=True
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="keyword_analysis",
            field=models.JSONField(
                blank=True,
                help_text="matched_keywords, missing_keywords, recommended_to_add",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="overall_grade",
            field=models.CharField(
                blank=True, help_text="Letter grade A-F", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="quick_wins",
            field=models.JSONField(
                blank=True, help_text="Array of priority/action objects", null=True
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="scores",
            field=models.JSONField(
                blank=True,
                help_text="generic_ats, workday_ats, greenhouse_ats, keyword_match_percent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="section_feedback",
            field=models.JSONField(
                blank=True, help_text="Array of per-section feedback objects", null=True
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="sentence_suggestions",
            field=models.JSONField(
                blank=True,
                help_text="Array of original/suggested/reason objects",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="summary",
            field=models.TextField(
                blank=True, help_text="2-3 sentence overall summary"
            ),
        ),
    ]
