# Generated by Django 4.2.16 on 2026-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0009_new_llm_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="credits_deducted",
            field=models.BooleanField(
                default=False,
                help_text="Whether credits were deducted for this analysis. Prevents double-deduction on Celery redelivery.",
            ),
        ),
    ]
