# Generated by Django 4.2.16 on 2026-02-26 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0010_resumeanalysis_credits_deducted"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedResume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template",
                    models.SlugField(
                        default="ats_classic",
                        help_text="Template slug (e.g. ats_classic, modern_clean)",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated resume file (stored in R2)",
                        upload_to="generated_resumes/",
                    ),
                ),
                (
                    "resume_content",
                    models.JSONField(
                        blank=True,
                        help_text="Structured resume JSON (contact, summary, experience, education, skills, etc.)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "credits_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether credits were deducted. Prevents double-deduction on retry.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The analysis whose findings drive the resume rewrite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_resumes",
                        to="analyzer.resumeanalysis",
                    ),
                ),
                (
                    "llm_response",
                    models.ForeignKey(
                        blank=True,
                        help_text="LLM response for the rewrite call",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_resumes",
                        to="analyzer.llmresponse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "-created_at"],
                        name="analyzer_ge_analysi_101262_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analyzer_ge_user_id_5d1722_idx",
                    ),
                ],
            },
        ),
    ]
