# Generated by Django 4.2.16 on 2026-02-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0011_generatedresume"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveredJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("serpapi", "SerpAPI (Google Jobs)"),
                            ("adzuna", "Adzuna"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Unique job ID from the source API", max_length=255
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("salary_range", models.CharField(blank=True, max_length=255)),
                (
                    "description_snippet",
                    models.TextField(
                        blank=True, help_text="Short job description excerpt"
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="Full raw API response for this job",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Alert preferences: remote_ok (bool), location (str), salary_min (int), excluded_companies (list)",
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        help_text="Resume used for job matching",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to="analyzer.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSearchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titles",
                    models.JSONField(
                        default=list, help_text="List of target job titles"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="Key skills extracted from resume"
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("executive", "Executive"),
                        ],
                        help_text="Seniority level inferred from resume",
                        max_length=20,
                    ),
                ),
                (
                    "industries",
                    models.JSONField(default=list, help_text="Target industries"),
                ),
                (
                    "locations",
                    models.JSONField(
                        default=list, help_text="Preferred work locations"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Years of experience inferred from resume",
                        null=True,
                    ),
                ),
                (
                    "raw_extraction",
                    models.JSONField(
                        blank=True,
                        help_text="Full LLM output for debugging / re-processing",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.OneToOneField(
                        help_text="Resume this profile was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_search_profile",
                        to="analyzer.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="JobMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.PositiveSmallIntegerField(
                        help_text="LLM relevance score 0-100"
                    ),
                ),
                (
                    "match_reason",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated reason why this job matches the resume",
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("relevant", "Relevant"),
                            ("irrelevant", "Irrelevant"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discovered_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="analyzer.discoveredjob",
                    ),
                ),
                (
                    "job_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="analyzer.jobalert",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAlertRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jobs_discovered", models.PositiveIntegerField(default=0)),
                ("jobs_matched", models.PositiveIntegerField(default=0)),
                ("notification_sent", models.BooleanField(default=False)),
                ("credits_used", models.PositiveSmallIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="analyzer.jobalert",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="discoveredjob",
            index=models.Index(
                fields=["source", "external_id"], name="analyzer_di_source_6a50c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredjob",
            index=models.Index(
                fields=["-created_at"], name="analyzer_di_created_2ad55a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="discoveredjob",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="unique_discovered_job_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["job_alert", "-relevance_score"],
                name="analyzer_jo_job_ale_54cc84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobmatch",
            index=models.Index(
                fields=["job_alert", "user_feedback"],
                name="analyzer_jo_job_ale_5590c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobmatch",
            constraint=models.UniqueConstraint(
                fields=("job_alert", "discovered_job"), name="unique_match_per_alert"
            ),
        ),
        migrations.AddIndex(
            model_name="jobalertrun",
            index=models.Index(
                fields=["job_alert", "-created_at"],
                name="analyzer_jo_job_ale_1f65e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobalert",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_jo_user_id_923ab5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobalert",
            index=models.Index(
                fields=["is_active", "next_run_at"],
                name="analyzer_jo_is_acti_710fec_idx",
            ),
        ),
    ]
