# Generated by Django 4.2.16 on 2026-02-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0012_discoveredjob_jobalert_jobsearchprofile_jobmatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalertrun",
            name="credits_deducted",
            field=models.BooleanField(
                default=False,
                help_text="Whether credits were deducted for this run (for idempotent refund)",
            ),
        ),
        migrations.AlterField(
            model_name="jobalert",
            name="resume",
            field=models.ForeignKey(
                help_text="Resume used for job matching",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_alerts",
                to="analyzer.resume",
            ),
        ),
    ]
