# Generated by Django 4.2.16 on 2026-02-27 09:48

from django.db import migrations, models
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0015_sentalert_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name (e.g. "LinkedIn", "Google Careers")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("job_board", "Job Board"),
                            ("company", "Company Career Page"),
                        ],
                        default="job_board",
                        help_text="Job board (uses {query}/{location} URL template) or company career page",
                        max_length=20,
                    ),
                ),
                (
                    "url_template",
                    models.CharField(
                        help_text="URL template with {query} and {location} placeholders for job boards. Plain URL for company career pages.",
                        max_length=2048,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive sources are skipped during crawl",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Lower = crawled first. Use to prioritise important sources.",
                    ),
                ),
                (
                    "last_crawled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful crawl",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Crawl Source",
                "verbose_name_plural": "Crawl Sources",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Job listing embedding for similarity matching",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobmatch",
            name="feedback_reason",
            field=models.TextField(
                blank=True,
                help_text="User-provided reason for their feedback (used in learning loop)",
            ),
        ),
        migrations.AddField(
            model_name="jobsearchprofile",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Resume text embedding for similarity matching",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredjob",
            name="source",
            field=models.CharField(
                choices=[("firecrawl", "Firecrawl")], db_index=True, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="jobalert",
            name="preferences",
            field=models.JSONField(
                default=dict,
                help_text="Alert preferences: remote_ok (bool), location (str), salary_min (int), excluded_companies (list), priority_companies (list)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Relative URL or external link for deep-linking",
                max_length=2048,
            ),
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
