# Generated by Django 4.2.16 on 2026-02-28 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0016_remove_job_add_crawlsource_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("conversational", "Conversational"),
                            ("enthusiastic", "Enthusiastic"),
                        ],
                        default="professional",
                        help_text="Desired tone for the cover letter.",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="The generated cover letter text."
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        help_text="HTML-formatted version of the cover letter.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated cover letter PDF (stored in R2).",
                        upload_to="cover_letters/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "credits_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether credits were deducted. Prevents double-deduction on retry.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cover Letter",
                "verbose_name_plural": "Cover Letters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewPrep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        blank=True,
                        help_text="Array of question objects: {category, question, why_asked, sample_answer, difficulty}",
                        null=True,
                    ),
                ),
                (
                    "tips",
                    models.JSONField(
                        blank=True,
                        help_text="General interview tips based on the analysis.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "credits_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether credits were deducted. Prevents double-deduction on retry.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Interview Prep",
                "verbose_name_plural": "Interview Preps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Sequential version number within this resume lineage.",
                    ),
                ),
                (
                    "change_summary",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or user-provided summary of changes.",
                        max_length=500,
                    ),
                ),
                (
                    "best_ats_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Best ATS score achieved with this resume version.",
                        null=True,
                    ),
                ),
                (
                    "best_grade",
                    models.CharField(
                        blank=True,
                        help_text="Best overall grade achieved with this resume version.",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume Version",
                "verbose_name_plural": "Resume Versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="call_purpose",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Purpose of this LLM call (analysis, resume_rewrite, job_matching, profile_extraction, job_extraction).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="completion_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of tokens in the completion (from API response.usage).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated cost in USD based on model pricing.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="prompt_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of tokens in the prompt (from API response.usage).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="total_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total tokens used (prompt + completion).",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="llmresponse",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_ll_user_id_13e52f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmresponse",
            index=models.Index(
                fields=["call_purpose", "-created_at"],
                name="analyzer_ll_call_pu_68a448_idx",
            ),
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="previous_resume",
            field=models.ForeignKey(
                blank=True,
                help_text="The previous version of this resume (NULL if first version).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="analyzer.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="resume",
            field=models.ForeignKey(
                help_text="The current resume in this version chain.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="analyzer.resume",
            ),
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interviewprep",
            name="analysis",
            field=models.ForeignKey(
                help_text="The analysis whose findings drive question generation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_preps",
                to="analyzer.resumeanalysis",
            ),
        ),
        migrations.AddField(
            model_name="interviewprep",
            name="llm_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_preps",
                to="analyzer.llmresponse",
            ),
        ),
        migrations.AddField(
            model_name="interviewprep",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_preps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="analysis",
            field=models.ForeignKey(
                help_text="The analysis whose findings inform the cover letter.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_letters",
                to="analyzer.resumeanalysis",
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="llm_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_letters",
                to="analyzer.llmresponse",
            ),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="resumeversion",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_re_user_id_2955ff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeversion",
            constraint=models.UniqueConstraint(
                fields=("user", "resume"), name="unique_version_per_resume"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewprep",
            index=models.Index(
                fields=["analysis", "-created_at"],
                name="analyzer_in_analysi_f7e35a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interviewprep",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_in_user_id_9798fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coverletter",
            index=models.Index(
                fields=["analysis", "-created_at"],
                name="analyzer_co_analysi_3cfb55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coverletter",
            index=models.Index(
                fields=["user", "-created_at"], name="analyzer_co_user_id_24de3b_idx"
            ),
        ),
    ]
