# Generated by Django 4.2.16 on 2026-02-28 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzer",
            "0017_add_token_tracking_interview_prep_cover_letter_resume_version",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name (e.g., "ATS Classic", "Modern Clean").',
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Template identifier used in API calls (e.g., "ats_classic", "modern").',
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description shown on the template marketplace.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("creative", "Creative"),
                            ("academic", "Academic"),
                            ("executive", "Executive"),
                        ],
                        default="professional",
                        help_text="Template category for filtering.",
                        max_length=20,
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Preview thumbnail shown in the template picker.",
                        upload_to="template_previews/",
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False,
                        help_text="Premium templates require a paid plan with premium_templates enabled.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden from the marketplace.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order in the marketplace (lower = first).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resume Template",
                "verbose_name_plural": "Resume Templates",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="share_token",
            field=models.UUIDField(
                blank=True,
                help_text="Public share token — when set, analysis is viewable at /api/v1/shared/<token>/",
                null=True,
                unique=True,
            ),
        ),
    ]
