# Generated by Django 4.2.16 on 2026-03-01 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0018_add_resume_template_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scratch", "Start Fresh"),
                            ("profile", "From Profile Data"),
                            ("previous", "From Previous Resume"),
                        ],
                        default="scratch",
                        max_length=20,
                    ),
                ),
                (
                    "resume_data",
                    models.JSONField(
                        default=dict,
                        help_text="Accumulated structured resume JSON (contact, experience, education, skills, etc.)",
                    ),
                ),
                ("target_role", models.CharField(blank=True, max_length=255)),
                ("target_company", models.CharField(blank=True, max_length=255)),
                ("target_industry", models.CharField(blank=True, max_length=100)),
                ("experience_level", models.CharField(blank=True, max_length=30)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("contact", "Contact Info"),
                            ("target_role", "Target Role"),
                            ("experience_input", "Experience Input"),
                            ("experience_review", "Experience Review"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("certifications", "Certifications"),
                            ("projects", "Projects"),
                            ("review", "Review & Polish"),
                            ("done", "Done"),
                        ],
                        default="start",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "credits_deducted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether credits were deducted for PDF/DOCX generation.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_resume",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resume used as base data (for source=previous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="builder_chats",
                        to="analyzer.resume",
                    ),
                ),
                (
                    "generated_resume",
                    models.ForeignKey(
                        blank=True,
                        help_text="Final generated resume file after finalize step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="builder_chat",
                        to="analyzer.generatedresume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Chat Session",
                "verbose_name_plural": "Resume Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Display text for the message bubble"
                    ),
                ),
                (
                    "ui_spec",
                    models.JSONField(
                        blank=True,
                        help_text="Structured UI specification for the frontend to render (type, fields, actions, etc.)",
                        null=True,
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        help_text="Partial resume_data extracted/updated in this turn",
                        null=True,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        blank=True,
                        help_text="Which wizard step this message belongs to",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="analyzer.resumechat",
                    ),
                ),
                (
                    "llm_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="analyzer.llmresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Chat Message",
                "verbose_name_plural": "Resume Chat Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat", "created_at"],
                        name="analyzer_re_chat_id_255286_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="resumechat",
            index=models.Index(
                fields=["user", "-updated_at"], name="analyzer_re_user_id_7cc134_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumechat",
            index=models.Index(
                fields=["user", "status"], name="analyzer_re_user_id_713ee1_idx"
            ),
        ),
    ]
