# Generated by Django 4.2.16 on 2026-03-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0019_add_resume_chat_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedresume",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                help_text="The analysis whose findings drive the resume rewrite (NULL for builder-created resumes)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_resumes",
                to="analyzer.resumeanalysis",
            ),
        ),
    ]
