# Generated by Django 4.2.16 on 2026-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0020_make_generated_resume_analysis_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="parsed_content",
            field=models.JSONField(
                blank=True,
                help_text="Structured resume data (contact, experience, education, skills, etc.) extracted from resume_text",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="pipeline_step",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pdf_extract", "Extracting PDF"),
                    ("jd_scrape", "Scraping JD"),
                    ("llm_call", "Calling LLM"),
                    ("parse_result", "Parsing Result"),
                    ("resume_parse", "Parsing Resume Data"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
