# Generated by Django 4.2.16 on 2026-03-01 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0021_add_parsed_content_to_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Brand / common name (e.g. "Google", "TCS", "Stripe")',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, auto-generated from name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief company description for display"
                    ),
                ),
                (
                    "logo",
                    models.URLField(
                        blank=True,
                        help_text="URL to company logo image",
                        max_length=2048,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("startup", "Startup (1-50)"),
                            ("small", "Small (51-200)"),
                            ("mid", "Mid-size (201-1000)"),
                            ("large", "Large (1001-10000)"),
                            ("enterprise", "Enterprise (10000+)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("headquarters_country", models.CharField(blank=True, max_length=100)),
                ("headquarters_city", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True, max_length=2048)),
                ("glassdoor_url", models.URLField(blank=True, max_length=2048)),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Known tech stack ["Python", "Kubernetes", ...]',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive companies are hidden from suggestions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="education_required",
            field=models.CharField(
                blank=True,
                help_text='Minimum education (e.g. "bachelor", "master", "none")',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="experience_years_max",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Maximum years of experience required", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="experience_years_min",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Minimum years of experience required", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="industry",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="remote_policy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onsite", "On-site"),
                    ("hybrid", "Hybrid"),
                    ("remote", "Remote"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="salary_max_usd",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="LLM-normalised annual salary upper bound in USD",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="salary_min_usd",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="LLM-normalised annual salary lower bound in USD",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="seniority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("intern", "Intern"),
                    ("junior", "Junior"),
                    ("mid", "Mid-level"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                    ("executive", "Executive"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="skills_nice_to_have",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Nice-to-have / preferred skills ["Go", "Terraform", ...]',
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="skills_required",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Required skills extracted from listing ["Python", "AWS", ...]',
            ),
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="source_page_url",
            field=models.URLField(
                blank=True,
                help_text="The search/career page URL we crawled to discover this job",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredjob",
            name="url",
            field=models.URLField(
                help_text="Direct link to the actual job posting / apply page",
                max_length=2048,
            ),
        ),
        migrations.CreateModel(
            name="CompanyEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text='Registered legal name (e.g. "Google India Pvt Ltd")',
                        max_length=500,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text='Short display name (e.g. "Google India", "Stripe US")',
                        max_length=255,
                    ),
                ),
                (
                    "operating_country",
                    models.CharField(
                        help_text='Country this entity operates in (e.g. "India", "United States")',
                        max_length=100,
                    ),
                ),
                ("operating_city", models.CharField(blank=True, max_length=100)),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False, help_text="Whether this entity is the global HQ"
                    ),
                ),
                (
                    "is_indian_entity",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Quick filter for Indian entities",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Corporate website for this entity (not brand site)",
                        max_length=2048,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Parent brand / company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="analyzer.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Entity",
                "verbose_name_plural": "Company Entities",
                "ordering": ["company", "operating_country"],
            },
        ),
        migrations.CreateModel(
            name="CompanyCareerPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text='Career page URL (e.g. "https://careers.google.com/jobs/")',
                        max_length=2048,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text='Label (e.g. "Engineering", "All Roles", "Campus")',
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country this page targets (may differ from entity country)",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crawl_frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="weekly",
                        help_text="How often to crawl this page",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        help_text="The entity this career page belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_pages",
                        to="analyzer.companyentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Page",
                "verbose_name_plural": "Career Pages",
                "ordering": ["entity", "label"],
            },
        ),
        migrations.AddField(
            model_name="discoveredjob",
            name="company_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Matched CompanyEntity record (linked post-crawl or via career page)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discovered_jobs",
                to="analyzer.companyentity",
            ),
        ),
        migrations.AddIndex(
            model_name="companyentity",
            index=models.Index(
                fields=["company", "operating_country"],
                name="analyzer_co_company_61c602_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyentity",
            index=models.Index(
                fields=["is_indian_entity"], name="analyzer_co_is_indi_e936c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyentity",
            constraint=models.UniqueConstraint(
                fields=("company", "operating_country", "display_name"),
                name="unique_entity_per_country",
            ),
        ),
    ]
