# Generated by Django 4.2.16 on 2026-03-01 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0022_add_company_models_enrich_discovered_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Calendar date (UTC) of the activity."),
                ),
                (
                    "action_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Total actions performed on this date."
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=dict,
                        help_text='Breakdown by action type, e.g. {"analysis": 2, "login": 1}.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="analyzer_us_user_id_165725_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
