# Generated by Django 4.2.16 on 2026-03-01 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analyzer", "0023_add_user_activity_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompanyFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[("follow", "Follow"), ("block", "Block")],
                        default="follow",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="analyzer.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Company Follow",
                "verbose_name_plural": "User Company Follows",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "relation"],
                        name="analyzer_us_user_id_b18110_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usercompanyfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_user_company_follow"
            ),
        ),
    ]
