# Generated by Django 4.2.16 on 2026-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0024_add_user_company_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumechat",
            name="mode",
            field=models.CharField(
                choices=[("text", "Text Chat"), ("guided", "Guided Wizard")],
                default="text",
                help_text="Chat mode: text (LLM conversation) or guided (step wizard)",
                max_length=10,
            ),
        ),
    ]
