# Generated by Django 4.2.16 on 2026-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0025_add_chat_mode_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredjob",
            name="source",
            field=models.CharField(
                choices=[
                    ("firecrawl", "Firecrawl"),
                    ("user_analysis", "User Analysis"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
