# Generated by Django 4.2.16 on 2026-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0026_add_user_analysis_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="The single default resume used for dashboard, feed, and personalisation.",
            ),
        ),
        migrations.AddConstraint(
            model_name="resume",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="unique_default_resume_per_user",
            ),
        ),
    ]
