# Generated by Django 4.2.16 on 2026-03-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0027_add_default_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredjob",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Normalised country name (e.g. "India", "United States"). Derived from location field or provided by crawler.',
                max_length=100,
            ),
        ),
    ]
