# Generated by Django 4.2.16 on 2026-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0028_add_country_to_discoveredjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="career_profile",
            field=models.JSONField(
                blank=True,
                help_text="Career matching profile (titles, skills, seniority, industries, locations, experience_years).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="parsed_content",
            field=models.JSONField(
                blank=True,
                help_text="Structured resume data (contact, experience, education, skills, etc.) extracted at upload time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="processing_error",
            field=models.TextField(
                blank=True, help_text="Error message if processing_status is failed."
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of the upload-time resume understanding pipeline.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_text",
            field=models.TextField(
                blank=True,
                help_text="Plain text extracted from the PDF at upload time.",
            ),
        ),
    ]
