# Generated by Django 4.2.16 on 2026-03-02 15:57

from django.db import migrations


def backfill_parsed_content(apps, schema_editor):
    """
    Backfill Resume.parsed_content from the latest ResumeAnalysis that has it.
    Also sets processing_status to 'done' for resumes that get backfilled.
    """
    Resume = apps.get_model('analyzer', 'Resume')
    ResumeAnalysis = apps.get_model('analyzer', 'ResumeAnalysis')

    resumes = Resume.objects.filter(parsed_content__isnull=True)
    updated = 0
    for resume in resumes.iterator():
        analysis = (
            ResumeAnalysis.objects
            .filter(
                resume=resume,
                status='done',
                deleted_at__isnull=True,
                parsed_content__isnull=False,
            )
            .order_by('-created_at')
            .first()
        )
        if analysis and analysis.parsed_content:
            resume.parsed_content = analysis.parsed_content
            resume.processing_status = 'done'
            resume.save(update_fields=['parsed_content', 'processing_status'])
            updated += 1

    if updated:
        print(f'  Backfilled parsed_content for {updated} resumes')


def reverse_backfill(apps, schema_editor):
    """Reverse: clear backfilled parsed_content on Resume."""
    Resume = apps.get_model('analyzer', 'Resume')
    Resume.objects.filter(processing_status='done').update(
        parsed_content=None, processing_status='pending',
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0029_add_resume_understanding_fields"),
    ]

    operations = [
        migrations.RunPython(backfill_parsed_content, reverse_backfill),
    ]
