# Generated by Django 4.2.16 on 2026-03-02 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0030_backfill_resume_parsed_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("situational", "Situational"),
                            ("role_specific", "Role-Specific"),
                            ("gap_based", "Gap-Based"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="The interview question text."),
                ),
                (
                    "why_asked",
                    models.TextField(
                        blank=True,
                        help_text="Why an interviewer would ask this. Supports {role}, {company} placeholders.",
                    ),
                ),
                (
                    "sample_answer_template",
                    models.TextField(
                        blank=True,
                        help_text="Sample answer template. Supports {role}, {company}, {skill} placeholders.",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text='Skill/keyword tags for matching, e.g. ["python", "leadership", "sql"]',
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        default=list,
                        help_text='Applicable role patterns, e.g. ["software engineer", "data analyst"]',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Interview Question",
                "verbose_name_plural": "Interview Questions",
                "ordering": ["category", "difficulty"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="analyzer_in_categor_ff552c_idx",
                    ),
                    models.Index(
                        fields=["difficulty", "is_active"],
                        name="analyzer_in_difficu_23534a_idx",
                    ),
                ],
            },
        ),
    ]
