# Generated by Django 4.2.16 on 2026-03-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0031_add_interview_question_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedresume",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                help_text="Resume created from this generated output — usable for analyses, alerts, feed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_from",
                to="analyzer.resume",
            ),
        ),
    ]
