# Generated by Django 4.2.16 on 2026-03-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0032_add_resume_fk_to_generated_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discoveredjob",
            name="source",
            field=models.CharField(
                db_index=True,
                help_text='Origin of the job posting (e.g. "firecrawl", "user_analysis").',
                max_length=30,
            ),
        ),
    ]
