# Generated by Django 4.2.16 on 2026-03-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0033_remove_source_choices_from_discoveredjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titles_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of sorted, lower-cased source titles — deduplication key.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "source_titles",
                    models.JSONField(
                        default=list,
                        help_text='Original titles from JobSearchProfile, e.g. ["Data Analyst", "BI Analyst"].',
                    ),
                ),
                (
                    "related_titles",
                    models.JSONField(
                        default=list,
                        help_text='LLM-generated related titles, e.g. ["Business Analyst", "Product Analyst", ...].',
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Role Family",
                "verbose_name_plural": "Role Families",
                "ordering": ["-generated_at"],
            },
        ),
    ]
