# Generated by Django 4.2.16 on 2026-03-04 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0034_add_role_family_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSnippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="Crawler bot primary key — upsert key on i-Luffy side.",
                        unique=True,
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                (
                    "summary",
                    models.TextField(help_text="2-3 sentence LLM-generated summary."),
                ),
                ("source_url", models.URLField(max_length=1000, unique=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hiring", "Hiring & Job Market"),
                            ("layoffs", "Layoffs & Restructuring"),
                            ("skill_demand", "Tech Skill Demand"),
                            ("salary", "Salary & Compensation"),
                            ("funding", "Startup & Funding"),
                            ("tech_news", "Tech News & Releases"),
                            ("ai_automation", "AI & Automation"),
                            ("trending_tech", "Trending Tech"),
                            ("job_tips", "Job Tips & Career Advice"),
                            ("dev_community", "Developer Community"),
                            ("big_tech", "Big Tech Moves"),
                            ("industry_report", "Industry Reports"),
                            ("visa_policy", "Visa & Immigration"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tag strings."
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=10,
                    ),
                ),
                (
                    "relevance_score",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="LLM-assigned 1-10 (10 = most relevant)."
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="e.g. India, US, Global", max_length=100
                    ),
                ),
                (
                    "company_mentions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Companies mentioned in the article.",
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "flag_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("low_relevance", "Low Relevance Score"),
                            ("inappropriate", "Inappropriate Content"),
                            ("spam", "Spam / Promotional"),
                            ("duplicate", "Duplicate Content"),
                            ("stale", "Stale / Outdated"),
                            ("unverified", "Unverified Source"),
                            ("dead_link", "Dead Link (404)"),
                            ("low_quality_negative", "Low Quality Negative"),
                            ("blocked_source", "Blocked Source Domain"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Snippet",
                "verbose_name_plural": "News Snippets",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-published_at"],
                        name="analyzer_ne_categor_b626e2_idx",
                    ),
                    models.Index(
                        fields=["region", "-published_at"],
                        name="analyzer_ne_region_76d17e_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_approved", "-published_at"],
                        name="analyzer_ne_is_acti_18c4af_idx",
                    ),
                    models.Index(
                        fields=["-relevance_score", "-published_at"],
                        name="analyzer_ne_relevan_b57500_idx",
                    ),
                ],
            },
        ),
    ]
