# Generated by Django 4.2.16 on 2026-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0035_add_news_snippet_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="retry_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of user-initiated retries. Free retries for system faults are capped at MAX_FREE_RETRIES.",
            ),
        ),
    ]
