# Generated by Django 4.2.16 on 2026-03-04 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0036_add_retry_count_to_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text='Canonical lowercase skill name (e.g. "python", "kubernetes").',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text='Pretty display name (e.g. "Python", "Kubernetes").',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated description of what this skill is.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Programming Language"),
                            ("framework", "Framework / Library"),
                            ("tool", "Tool / Platform"),
                            ("cloud", "Cloud / Infrastructure"),
                            ("data", "Data / Database"),
                            ("devops", "DevOps / CI-CD"),
                            ("design", "Design / UX"),
                            ("soft", "Soft Skill"),
                            ("security", "Security"),
                            ("mobile", "Mobile"),
                            ("ai_ml", "AI / Machine Learning"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Skill category for grouping / filtering.",
                        max_length=20,
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Alternate names for dedup (e.g. ["k8s", "kube"] → kubernetes).',
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Common roles that use this skill, e.g. ["backend engineer", "devops"].',
                    ),
                ),
                (
                    "job_count_5y",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Jobs mentioning this skill in the last 5 years.",
                    ),
                ),
                (
                    "job_count_1y",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Jobs mentioning this skill in the last 1 year.",
                    ),
                ),
                (
                    "job_count_30d",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Jobs mentioning this skill in the last 30 days.",
                    ),
                ),
                (
                    "growth_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Demand growth %: (count_30d - prev_30d) / prev_30d * 100.",
                        null=True,
                    ),
                ),
                (
                    "avg_salary_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average salary (USD) for jobs requiring this skill.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_trending",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set by aggregate_skills for top-demand skills.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "last_aggregated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When job counts were last refreshed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["-job_count_30d", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "-job_count_30d"],
                        name="analyzer_sk_categor_a20ef7_idx",
                    ),
                    models.Index(
                        fields=["is_trending", "-job_count_30d"],
                        name="analyzer_sk_is_tren_3da173_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-job_count_30d"],
                        name="analyzer_sk_is_acti_718fad_idx",
                    ),
                ],
            },
        ),
    ]
