# Generated by Django 4.2.16 on 2026-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0037_add_skill_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedresume",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-editable label for this generated resume.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-editable label. When blank, UI falls back to original_filename.",
                max_length=255,
            ),
        ),
    ]
